# Generated by Django 6.0 on 2026-01-06 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.CharField(choices=[('first trip', 'First Trip'), ('second trip', 'Second Trip')], max_length=50)),
                ('police_station', models.CharField(blank=True, max_length=160, null=True)),
                ('car_number', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=299)),
                ('location', models.CharField(max_length=300)),
                ('wheels', models.IntegerField()),
                ('cft', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('payment_in', models.CharField(choices=[('upi', 'Upi'), ('cash', 'Cash')], max_length=50)),
                ('paid_amount', models.FloatField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=50)),
                ('remarks', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
