# Generated by Django 6.0 on 2026-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceuser',
            name='is_system',
        ),
        migrations.AddField(
            model_name='invoiceuser',
            name='is_admin',
            field=models.BooleanField(default=True, help_text='Represent The Normal User'),
        ),
        migrations.AddField(
            model_name='invoiceuser',
            name='is_coofficer',
            field=models.BooleanField(default=False, help_text='Represent The Co-Officer'),
        ),
        migrations.AddField(
            model_name='invoiceuser',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Represent The Super Admin User'),
        ),
        migrations.AddField(
            model_name='invoiceuser',
            name='is_ultraadmin',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a Ultraadmin user.'),
        ),
    ]
