# Generated by Django 6.0 on 2026-01-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivg', '0003_vendors_invoicedata_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedata',
            name='file_url',
        ),
    ]
